### ISSUE TITLE
Add Aegis Wallet to wallets available for Android

### ISSUE THREAD

**Issue by bsimic0001** [bitcoin/bitcoin.org#445]
There is a new free and open source wallet for Android that focuses on security. 

It should be added to the list of wallets available for Android. More info can be found at this URL: http://www.aegiswallet.com/

The page in question is:
https://bitcoin.org/en/choose-your-wallet

**Comment by harding** [comment]
The [webpage for this wallet](http://www.aegiswallet.com/) is now a GoDaddy placeholder page, the GitHub repository hasn't been updated in over two months, and the [Google Play](https://play.google.com/store/apps/details?id=com.aegiswallet) last update is also more than two months old.

I think this wallet may be dead, so I'm closing this issue.  We can reopen it if anything changes.

**Comment by saivann** [comment]
Thanks, makes sense. The last release 1.1.4.0 wasn't tagged on GitHub also. I was also generally uncertain if the app was maintained given the quite small activity, although developers were apparently responsive previously.

**Comment by hyprkey** [comment]
I'm still developing the app.

However, the guy who volunteered to maintain the official website has
dropped off and I am trying to gain access of the domain from him to put
the site back up.

I am working on a big release to make the wallet HD.

-Bojan

On Tue, Jan 27, 2015 at 7:12 PM, saivann <notifications@github.com> wrote:

> Thanks, makes sense. The last release 1.1.4.0 wasn't tagged on GitHub
> also. I was also generally uncertain if the app was maintained given the
> quite small activity, although developers were apparently responsive
> previously.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitcoin/bitcoin.org/issues/445#issuecomment-71756721>.
>



-- 

*Bojan Simic | 859-552-3186 | @bojansimicChief Technology Officer *


* <https://www.hyprkey.com/>*
<http://blog.hyprkey.com/>  <https://twitter.com/HyprKey>
<https://www.facebook.com/hyprkey>  <https://plus.google.com/+Hyprkey/posts>
  <https://www.linkedin.com/company/hyprkey>
<http://www.youtube.com/user/HyprKey>  <http://instagram.com/hyprkey/>

**Comment by harding** [comment]
@hyprkey ok, reopening.  My apologies for closing without discussion.

**Comment by hyprkey** [comment]
Thanks David.

I hope to have the site back up ASAP.



On Tue, Jan 27, 2015 at 7:46 PM, David A. Harding <notifications@github.com>
wrote:

> Reopened #445 <https://github.com/bitcoin/bitcoin.org/issues/445>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitcoin/bitcoin.org/issues/445#event-225774915>.
>



-- 

*Bojan Simic | 859-552-3186 | @bojansimicChief Technology Officer *


* <https://www.hyprkey.com/>*
<http://blog.hyprkey.com/>  <https://twitter.com/HyprKey>
<https://www.facebook.com/hyprkey>  <https://plus.google.com/+Hyprkey/posts>
  <https://www.linkedin.com/company/hyprkey>
<http://www.youtube.com/user/HyprKey>  <http://instagram.com/hyprkey/>

**Comment by harding** [comment]
Closing.  We are now asking that new wallets proposed for the Choose Your Wallet page be submitted as a pull request.  Instructions are available here: https://github.com/bitcoin/bitcoin.org#wallets

Please let us know if you need any help, and sorry for any inconvenience.
