### ISSUE TITLE
Bitcoin Conference Russia

### ISSUE THREAD

**Issue by antizvuk** [bitcoin/bitcoin.org#599]
date: 2015-04-23
title: by "SMILE-EXPO"
city: Moscow
country: Russia
link: http://bitcoinconf.ru/ru

**Comment by harding** [comment]
Even though it has a somewhat different date, this appears to be the same conference as added in issue #743 / commit f5d627f, so I'm going to close this issue.  @antizvuk if this is a different conference, please comment and I'll re-open the issue.  Thanks!
