### ISSUE TITLE
Vagrant VM for a Consistent and Optimized Development Environment

### ISSUE THREAD

**Issue by i3inary** [bitcoin/bitcoin.org#653]
I would like to suggest my project (https://github.com/i3inary/bitcoin.org-vagrant-jekyll-box
) to use to make sure new web devs don't have to spend days trying to get Jekyll working like I did.  My intentions were to contribute it to the project and reduce the barrier to entry for other web devs having trouble running or not familiar with Jekyll.  I myself had loads of issues getting this working on my local env and gave up and went with a virtual machine.

On a side note I would love to get this thing adding the .html extensions for the webserver and also get the compiling to only detect changes...this just will not work for me.  Any suggestions would be awesome and I will update the project.

**Comment by coderwill** [comment]
Perhaps we can close this issue. It has been idle for a while, and even if we were using a virtualized environment, there is still a chance that due to different levels of experience potential contributors could have difficulties setting up and using that correctly the first time, too.

**Comment by harding** [comment]
I'll close this a week from now (May 29th) if there's no further activity.
