### ISSUE TITLE
INTERNATIONAL BLOCKCHAIN SUMMIT

### ISSUE THREAD

**Issue by collinlahay** [bitcoin/bitcoin.org#668]
- date: 2015-01-21
      title: "INTERNATIONAL BLOCKCHAIN SUMMIT"
      venue: ""
      address: ""
      city: "George Town"
      country: "Grand Cayman"
      link: "http://latitude.global/"

**Comment by saivann** [comment]
Closing this issue since the event is tomorrow and address is still unknown.
