### ISSUE TITLE
The Atlanta Bitcoin Consumer Fair

### ISSUE THREAD

**Issue by privacymaverick** [bitcoin/bitcoin.org#683]
- date: 2015-04-17
      title: "The Atlanta Bitcoin Consume Fair"
      venue: ""
      address: ""
      city: "Atlanta, GA"
      country: "United States"
      link: "http://www.bitcoinconsumerfair.com"

**Comment by harding** [comment]
Closing, event added in https://github.com/bitcoin/bitcoin.org/commit/228344fb0db481710918d8a55d722242cbf07a90
