### ISSUE TITLE
Ledger Wallet!

### ISSUE THREAD

**Issue by MuhammedZakir** [bitcoin/bitcoin.org#696]
Hello! I found **HW.1** and **TREZOR** in Hardware Wallets. But why isn't **Ledger Wallet** and *Hardbit* not shown? *Hardbit* can be avoided as it isn't open source and thus, might be insecure to use it but **Ledger** is open source and verified as good. Thanks!

Kindly,
      Muhammed Zakir

**Comment by btchip** [comment]
yes, I plan to do that, also update the picture. We'll be on this shortly (read, at some point in January). Happy new year to you all by the way :)

**Comment by MuhammedZakir** [comment]
@btchip Thanks for replying! As it this is now solved, shall I close this?

**Comment by saivann** [comment]
@MuhammedZakir I think keeping your issue open until the wallet has been renamed would be useful, thanks!

**Comment by MuhammedZakir** [comment]
@saivann Sure! I am not closing this. Why isn't Hardbit listed? Is it because it isn't open source? Sorry for the disturbance caused.

**Comment by saivann** [comment]
@MuhammedZakir Hardbit can be submitted separately if you think it is worth listing. This being said I think there is blocking issues that would prevent it from being listed. I can't find much public feedback about it and the app indeed seems closed-source without public specification although it's not using a Secure Element, it's apparently just a Android phone with a custom ROM and it's unclear if the firmware and app receive security updates.

**Comment by saivann** [comment]
@btchip Just a reminder :) Do you still plan to update your description, title and picture?

**Comment by btchip** [comment]
yes, I'll push that to the team next week. Forgot it, thanks for the reminder.

**Comment by btchip** [comment]
Eric finally got to it, sorry about the long wait.

**Comment by MuhammedZakir** [comment]
@btchip Thank You!
