### ISSUE TITLE
Note for running nodes on OSX - disable display sleep & screensaver

### ISSUE THREAD

**Issue by bitofalefty** [bitcoin/bitcoin.org#698]
Something I've noticed is that, when running a node on OSX (10.9.3) the ping time goes through the roof whenever the user account is 'locked' or the screensaver comes on, going up to about 10 seconds. I guess the machine is going into some sort of low power mode. The problem is that it isn't obvious at all to the casual node runner. Setting the display sleep to 'never' solved this problem for me and the latency is now below 100ms.

It may be worth adding a small note to the download page for OSX to disable display sleep (and computer sleep) to avoid this, if the user is interested in helping the network as much as possible.

**Comment by saivann** [comment]
@harding This could go into the upcoming "Run your full node" page maybe? I guess this could be mentioned shortly for any platform, for example "Make sure your computer does not automatically go into sleep mode".

**Comment by harding** [comment]
@saivann yes, I'll be sure to mention it on that page.  Thanks!
