### ISSUE TITLE
The BitPanel – Mobile Apps Edition

### ISSUE THREAD

**Issue by dcawrey** [bitcoin/bitcoin.org#701]
- date: 2015-01-14
      title: "BitPanel Mobile Apps Edition"
      venue: "Hero City at Draper University"
      address: "55 3rd Ave"
      city: "San Mateo"
      country: "USA"
      link: "http://www.eventbrite.com/e/bitpanel-the-mobile-apps-edition-tickets-15118137757"

**Comment by saivann** [comment]
@dcawrey Thanks, the event should be published in the next minutes.
