### ISSUE TITLE
Chambe-Carnet: Bitcoin, initiation à l’argent P2P et opportunités

### ISSUE THREAD

**Issue by fbrun** [bitcoin/bitcoin.org#702]
- date: 2015-02-26
      title: "Chambe-Carnet: Bitcoin, initiation à l’argent P2P et opportunités"
      venue: ""
      address: "The exact location to be decided"
      city: "Chambery (Savoie)"
      country: "France"
      link: "http://www.chambe-carnet.com/2015/01/06/bitcoin-initiation-a-largent-p2p-et-opportunites/"

**Comment by saivann** [comment]
@fbrun Thanks, can you comment here once the venue and address is available?

**Comment by fbrun** [comment]
@saivann yes as soon as I have the information, i put it here

**Comment by fbrun** [comment]
@saivann, Hi,

here the informations missing:

venue: "'Horloge' building, hall 'Mur Jericho'"
address: "Savoie Technolac,16 avenue Lac du Bourget 73374 Le Bourget-du-Lac France"

Thanks

**Comment by harding** [comment]
@fbrun the event should appear on the website in a few minutes.  Thanks!

**Comment by fbrun** [comment]
Ok great
