### ISSUE TITLE
The Stag Night - Bitcoin Crowdfunding Party in Berlin

### ISSUE THREAD

**Issue by Kalifilm** [bitcoin/bitcoin.org#703]
- date: 2014-01-08
      title: "The Stag Night - Bitcoin Crowdfunding Party in Berlin"
      venue: "Cosmic Kaspar @ Mein Haus am See"
      address: "Brunnenstr. 197-198, 10119 Berlin"
      city: "Berlin"
      country: "Germany"
      link: "https://www.facebook.com/events/1576511895918419/"

![party poster](https://cloud.githubusercontent.com/assets/10417197/5628052/feeb9364-95a1-11e4-90c9-5eb1c7105f4c.png)

**Comment by saivann** [comment]
@Kalifilm Thanks, unfortunately the event is now in the past. If you plan to publish other events in the future, I suggest you do it at least 2 weeks before the event is taking place.
