### ISSUE TITLE
Outdated input size limit for standard transactions

### ISSUE THREAD

**Issue by gsalgado** [bitcoin/bitcoin.org#705]
Location: https://bitcoin.org/en/developer-guide#non-standard-transactions

The non-standard tx section states that (As of Bitcoin Core 0.9): "Each of the transaction’s inputs must be smaller than 500 bytes. That’s large enough to allow 3-of-3 multisig transactions in P2SH. Multisig transactions which require more than 3 public keys are currently non-standard."

But that doesn't seem to be the case: https://github.com/bitcoin/bitcoin/blob/0.9/src/main.cpp#L543

**Comment by harding** [comment]
@gsalgado thanks for another excellent bug report!  Commit 2d46b41 should fix this (it will go live in a few minutes).  Thanks again!
