### ISSUE TITLE
VipIMAGE 2015

### ISSUE THREAD

**Issue by jmrstavares** [bitcoin/bitcoin.org#708]
- date: 2015-10-19
      title: "V ECCOMAS Thematic Conferences on Computational Vision and Medical Image Processing"
      venue: "H10 Costa Adeje Palace"
      address: "Playa La Enramada, La Caleta"
      city: "Tenerife"
      country: "Spain"
      link: "http://www.fe.up.pt/vipimage"

**Comment by harding** [comment]
@jmrstavares thanks for submitting the event.  Could you briefly describe what the event has to do with Bitcoin?  From the website, it looks like a medical conference to me.

**Comment by jmrstavares** [comment]
Hi,

It is on medical imaging / computer vision.

Thank you very much.

João


On 14 Jan 2015, at 20:33, David A. Harding <notifications@github.com> wrote:

@jmrstavares <https://github.com/jmrstavares> thanks for submitting the event. Could you briefly describe what the event has to do with Bitcoin? From the website, it looks like a medical conference to me.

—
Reply to this email directly or view it on GitHub <https://github.com/bitcoin/bitcoin.org/issues/708#issuecomment-69986390>.



___________________________________________________________________________
                               João Manuel R. S. Tavares, MSc, PhD
 
     Faculdade de Engenharia, Universidade do Porto (FEUP)
     Departamento de Engenharia Mecânica (DEMec)
     Rua Dr. Roberto Frias, s/n , 4200-465 PORTO, PORTUGAL
 
     Phone: +351 22 508 3472, FAX: +351 22 508 1445
     Mobile: +351 93 420 1076, Skype: jmrstavares
 
     e-mail: tavares@fe.up.pt <mailto:tavares@fe.up.pt>, url: www.fe.up.pt/~tavares <http://www.fe.up.pt/~tavares>,
     Facebook: www.facebook.com/jmrstavares <http://www.facebook.com/jmrstavares>,
     Linkedin: www.linkedin.com/pub/jo%C3%A3o-manuel-r-s-tavares/5a/656/934 <http://www.linkedin.com/pub/jo%C3%A3o-manuel-r-s-tavares/5a/656/934>,
     Twitter: twitter.com/jmrstavares <http://twitter.com/jmrstavares>  
 
     Editor-In-Chief: T&F CMBBE: Imaging & Visualization - www.tandfonline.com/tciv <http://www.tandfonline.com/tciv>
 
     Co-Editor: SPRINGER book series LNCV&B - www.springer.com/series/8910 <http://www.springer.com/series/8910>
 
     Co-Chair: ECCOMAS VipIMAGE - www.fe.up.pt/~vipimage <http://www.fe.up.pt/~vipimage>
     Co-Chair: CompIMAGE - www.fe.up.pt/CompIMAGE <http://www.fe.up.pt/CompIMAGE>
     Co-Chair: ICCEBS - www.fe.up.pt/~iccebs <http://www.fe.up.pt/~iccebs>
     Co-Chair: BioDENTAL - www.fe.up.pt/~biodenta <http://www.fe.up.pt/~biodenta>
___________________________________________________________________________

**Comment by harding** [comment]
Ok.  That doesn't sound Bitcoin related, so I'm going to close this request.  If you have anything to add, please feel to post a comment and we can re-open the request.  Thanks.
