### ISSUE TITLE
MTBIT - Bitcoin & Remittances Las Vegas

### ISSUE THREAD

**Issue by hcmohr** [bitcoin/bitcoin.org#716]
![mtbit](https://cloud.githubusercontent.com/assets/10673828/5879481/b704a6da-a2fd-11e4-9a02-d54be5d38883.png)
2015-03-23
MTBIT - Bitcoin & Remittances Las Vegas
Flamingo Hotel & Casino
3555 Las Vegas Boulevard South
Las Vegas, NV
United States
http://www.imtconferences.com/mtbit/

**Comment by saivann** [comment]
@hcmohr Thanks, your event should be displayed in the next minutes.

**Comment by hcmohr** [comment]
Thank you!
