### ISSUE TITLE
BIP0050 description not correct.

### ISSUE THREAD

**Issue by instagibbs** [bitcoin/bitcoin.org#719]
Source File: _includes/guide_block_chain.md

I'm writing up this issue before I forget I saw it. The writeup is actually based on the old and incorrect understanding of what happened. Apparently the fork dealt with intra-version database issues and not inter-version incompatibilities. 

I need to find my citation for this, but it has come up a few times in -wizards/-devs/elsewhere.

**Comment by instagibbs** [comment]
Actually I misread what it said. Nevermind this for now sorry.

**Comment by harding** [comment]
@instagibbs thanks anyway!  (Issues that close themselves before I even see them are my favorite kind. :-)
