### ISSUE TITLE
Bitcoin First Friday Event

### ISSUE THREAD

**Issue by R-HirojaTrevize** [bitcoin/bitcoin.org#729]
- date: 2015-02-06
      title: "Bitcoin First Friday Event"
      venue: "Raw Remedies Gallery"
      address: "203 COLORADO AVE"
      city: "Las Vegas, Nevada"
      country: "USA"
      link: "https://www.facebook.com/events/749536845128074/"

**Comment by R-HirojaTrevize** [comment]
This event the first of series of  Cryptocurrency gatherings  in Downtown Las Vegas Nevada sponsor by Dogecoin Shop . These events coincide with a City Wide held event known as First Friday held in the area call 18B Art District in Downtown Las Vegas Nevada.  These gatherings are use to promote the businesses already accepting Cryptocurrency  in the 18B Art District in Downtown Las Vegas Nevada and educate the general public about Cryptocurrency.

The First Friday Event has 20-30k people in attendance it is an event held  like the name states every month through out the year. Las Vegas Is a Major International Tourist Destination and a rising Global Tech Hub. To have Dogecoin Shop sponsor events like these to bring cryptocurrency to an the general/international  public brings greater awareness to Cryptocurrency and increase the opportunity for mass adoption by people everywhere.

**Comment by harding** [comment]
@R-HirojaTrevize thanks for submitting the event!  It should appear on the website within about 15 minutes.
