### ISSUE TITLE
Bitcoin Wednesday Conference Amsterdam - 1st Wednesday of the Month

### ISSUE THREAD

**Issue by generalseven** [bitcoin/bitcoin.org#739]
- date: 06-05-2015
      title: "Bitcoin Wednesday"
      venue: "Pakhuis de Zwijger"
      address: "Piet Heinkade 179"
      city: "Amsterdam"
      country: "The Netherlands"
      link: "www.BitcoinWednesday.com"

**Comment by harding** [comment]
@generalseven thanks for submitting the event!  I notice that you also have a [meetup page](http://www.meetup.com/BitcoinWednesday/).  If you change the address on that page to be shown to the public, all of your events with "Bitcoin" in the title will be automatically shown on the Bitcoin.org events map after the next time we update the site.

If that's not possible, let me know and I'll add your submission above to the events list manually.

**Comment by generalseven** [comment]
Hi David, great to meet you.  For now that's not possible.  The location
does not change often, but best information about our conferences can be
found at BitcoinWednesday.Com.  Please link there.

Regards,
Richard

**Comment by harding** [comment]
@generalseven this event should appear on the website within about 15 minutes.  Thanks again!

**Comment by generalseven** [comment]
@harding I noticed our event had not been listed, and resubmitted with:

https://github.com/bitcoin/bitcoin.org/issues/906

This is a recurring event on the first Wednesday of the month, and 1 July will be our 2 Year Anniversary edition.

After that, it will be held on:

5 August
2 September
7 October
4 November
2 December

and so on, hopefully well into the next century.  ;)
