### ISSUE TITLE
Bitcoin - Pirate Payments Systems, Cryptocurrencies, and Disruption in Finance

### ISSUE THREAD

**Issue by mach5des** [bitcoin/bitcoin.org#741]
- date: 2015-02-26
      title: "Pirate Payments Systems, Cryptocurrencies, and Disruption in Finance"
      venue: "General Assembly"
      address: "225 Bush Street 5th Floor"
      city: "San Francisco"
      country: "USA"
      link: "https://www.eventbrite.com/e/pirate-payments-systems-cryptocurrencies-and-disruption-in-finance-tickets-15238621126?discount=insider"

**Comment by harding** [comment]
@mach5des thanks for submitting your event!  It should appear on the website within about 15 minutes.

**Comment by mach5des** [comment]
Thanks.


On Sun, Feb 8, 2015 at 9:06 AM, David A. Harding <notifications@github.com>
wrote:

> Closed #741 <https://github.com/bitcoin/bitcoin.org/issues/741>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitcoin/bitcoin.org/issues/741#event-232117971>.
>



-- 
Gregory Kennedy
415-341-5762
www.linkedin.com/in/gregorykennedy/
