### ISSUE TITLE
New events please

### ISSUE THREAD

**Issue by voffkas** [bitcoin/bitcoin.org#743]
- date: 2015-04-02
  title: "Bitcoin Conference Russia 2015"
  venue: "MSU Science Park"
  address: "Buildings 75, Leninskie Gory"
  city: "Moscow"
  country: "Russia"
  link: "http://bitcoinconf.moscow/"

- date: 2015-05-14
  title: "Bitcoin Conference Prague 2015"
  venue: "Prague Congress Centre"
  address: "Prague 5, Kvetna 65"
  city: "Prague"
  country: "Czech Republic"
  link: "http://bitcoinconf.eu/"

**Comment by harding** [comment]
@voffkas Thanks for submitting the events!  They should appear on the website within about 15 minutes.
