### ISSUE TITLE
Coin Debut at SXSW

### ISSUE THREAD

**Issue by mollywaldron** [bitcoin/bitcoin.org#744]
- date: 2015-03-15
      title: Coin Debut at SXSW
      venue: Max's Wine Dive
      address: 207 San Jacinto Blvd
      city: Austin, TX
      country: USA
      link: http://coindebut.com/

**Comment by harding** [comment]
@mollywaldron thanks for submitting the event!  It should be displayed on the website within about 15 minutes.
