### ISSUE TITLE
The State of Digital Money

### ISSUE THREAD

**Issue by alanlungtse** [bitcoin/bitcoin.org#745]
- date: 2015-04-18
      title: "The State of Digital Money"
      venue: "Rhubarb Studios"
      address: "633 W 5th St"
      city: "Los Angeles"
      country: "United States"
      link: "http://www.cureativ.com/sodm#digitalmoney"

**Comment by harding** [comment]
@alanlungtse thanks for submitting your event!  It should appear on the website within about 15 minutes.
