### ISSUE TITLE
Torrent has non-descriptive name "0.10.0"

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin.org#748]
Just a suggestion, nothing urgent, but for next release it'd make sense to include "Bitcoin Core" somewhere in the name
![torrent](https://cloud.githubusercontent.com/assets/126646/6210255/bb2269e8-b5c5-11e4-8b67-da90b307d867.png)

**Comment by saivann** [comment]
This would require we use something like /bin/bitcoin-0.10.1 as a naming
scheme on bitcoin.org for next releases. The torrent name must be the same
as the root folder for webseeding.

**Comment by laanwj** [comment]
Right - makes sense

**Comment by saivann** [comment]
Unless someone disagrees, I will prefix the folders with "bitcoin-" when I get time before next release (and add a temporary virtual directory to not break the existing torrent).

**Comment by harding** [comment]
@saivann I don't think we're low on text space, so it may be even more informative to prefix with `bitcoin-core-`

Otherwise, sounds good to me.

**Comment by saivann** [comment]
@harding Makes sense. Actually this could apply to the filenames as well (although I don't know if it's worth a pull request on the Bitcoin Core repository). The releases have historically always used the bitcoin-{version].tar.gz nomenclature. The project was only renamed Bitcoin-Qt, and then Bitcoin Core, in the recent years.

**Comment by saivann** [comment]
I have just updated the /bin/ directory naming scheme, made sure previous links would still work, and tested it against the updated torrent generator script. Thanks for reporting the issue!

**Comment by harding** [comment]
@saivann with regard to this change, what directory should @laanwj be putting the new releases in?  The release notes for upcoming version 0.10.1 currently say:

> Bitcoin Core version 0.10.1 is now available from:
> 
>  <https://bitcoin.org/bin/0.10.1/>

If you let me know, I'll submit a PR updating Bitcoin Core's 0.10.1 release notes and release documentation.

**Comment by saivann** [comment]
@harding Good catch, it should now be as follow: https://bitcoin.org/bin/bitcoin-core-0.10.1/

**Comment by harding** [comment]
@saivann thanks!  I'll work on that Bitcoin Core PR right now.
