### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by robynfarah** [bitcoin/bitcoin.org#754]
- date: 2015-19-02
      title: "KAT-O Tech Talk: From Fiction to Science: cover string Theory and Bitcoins"
      venue: "City Varsity"
      address: "18-22 Roeland Street"
      city: "Cape Town"
      country: "South Africa"
      link: "https://www.eventbrite.com/e/tech-talk-from-fiction-to-science-covering-the-string-theory-and-bitcoins-tickets-15678696403"

**Comment by harding** [comment]
@robynfarah thank you for submitting your event, but we don't usually publish events that are happening today.  I do hope you have fun though!

**Comment by robynfarah** [comment]
No problem. I just saw your website this morning.
Best,
Robyn
