### ISSUE TITLE
Atlanta Bitcoin Consumer Fair

### ISSUE THREAD

**Issue by privacymaverick** [bitcoin/bitcoin.org#769]
- date: 2015-04-18
      title: "Atlanta Bitcoin Consumer Fair"
      venue: "Loudermilk Conference Center"
      address: "40 Courtland Street NE"
      city: "Atlanta, GA"
      country: "USA"
      link: "http://bitcoinconsumerfair.com/"

**Comment by saivann** [comment]
@privacymaverick Thanks for submitting the event. It should be published in the next minutes!
