### ISSUE TITLE
Decentralize This! Bitcoin Hackathon

### ISSUE THREAD

**Issue by boazeb** [bitcoin/bitcoin.org#772]
- date: 2015-03-12
      title: "Decentralize This! Hackathon"
      venue: " Lool.vc HQ"
      address: "2 Tushyia Street"
      city: "Tel Aviv"
      country: "Israel"
      link: "http://decentralize-this-hackathon.weebly.com/"

**Comment by harding** [comment]
@boazeb thanks for submitting your event!  (It looks like a lot of fun!)  It should appear on the website within about 15 minutes.
