### ISSUE TITLE
windows 8.1

### ISSUE THREAD

**Issue by ClickInno** [bitcoin/bitcoin.org#775]

**Comment by harding** [comment]
Hi, @ClickInno!  If you want to help provide instructions for Windows 8.1, please see issue #763: `https://github.com/bitcoin/bitcoin.org/issues/763`

Don't worry about submitting duplicate instructions or screenshots---I can use any and all information.  (I'm going to close this issue, if you have any questions or comments, please put them on issue #763)  Thanks!
