### ISSUE TITLE
Future of Money - The Bitcoin Story

### ISSUE THREAD

**Issue by goenkas** [bitcoin/bitcoin.org#782]
- date: 2015-03-19
      title: "Future of Money - The Bitcoin Story"
      venue: "YMCA Ahmedabad, India"
      address: "YMCA International Center, SG Highway, Ahmedabad 380015, India"
      city: "Ahmedabad"
      country: "India"
      link: "getmagnet.co/future-of-money"

**Comment by harding** [comment]
Merged in 76fd57dac.  @goenkas thanks for submitting your event!  It should appear on the website within about 15 minutes.
