### ISSUE TITLE
MIT Bitcoin Expo

### ISSUE THREAD

**Issue by Firescar96** [bitcoin/bitcoin.org#785]
- date: 2015-03-07
      title: "MIT Bitcoin Expo"
      venue: "MIT Compton Labs"
      address: "60 Vassar Street"
      city: "Cambridge"
      country: "USA"
      link: "mitbitcoinexpo.org"

**Comment by harding** [comment]
@Firescar96 added in commit https://github.com/bitcoin/bitcoin.org/commit/d44692c75b0623768be112fed328d8d5c267ce47 The event should appear on the website within about 15 minutes.  Thanks!
