### ISSUE TITLE
Bitcoinference 2015

### ISSUE THREAD

**Issue by Bitcoinference** [bitcoin/bitcoin.org#791]
+ date: 2015-05-30
   title: "Bitcoinference 2015"
   venue: "Berlage Meet & Workpace"
   address: "Oudebrugsteeg 9, 1012 JN"
   city: "Amsterdam"
   country: "Netherlands"
   link: "http://bitcoinference.com/"

**Comment by harding** [comment]
@Bitcoinference the event is now listed on the site.  Thanks for submitting it!

Commit ref: https://github.com/bitcoin/bitcoin.org/commit/49071f766b393570d19088fe45a131651a1c8e9f

**Comment by Bitcoinference** [comment]
OK, thanks!
