### ISSUE TITLE
addr links are wrong

### ISSUE THREAD

**Issue by larshesel** [bitcoin/bitcoin.org#792]
Location: https://bitcoin.org/en/developer-reference#addr

For example in the address section, there are links to the addr message, but the link points to the alert section: https://bitcoin.org/en/developer-reference#alert

**Comment by gurnec** [comment]
@harding I was actually just about to submit a PR for this, but since you're looking at it now I won't bother. As I'm sure you'll see it looks like a copy/paste error in _includes/references.md.

**Comment by harding** [comment]
@gurnec thanks!  Actually, I'll pull your commit 7f4a590 since that was the exact change I was planning to make.

I'm updating the build server in prep for PR #789, and this will go in as soon as I verify that's working.

**Comment by harding** [comment]
@larshesel this should now be fixed.  Thanks for reporting!  (And thanks again @gurnec for fixing!)

**Comment by larshesel** [comment]
@harding just checked, looks good, thanks!
