### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by ConsumersResearch** [bitcoin/bitcoin.org#794]
- date: 2015-04-22
      title: "The Age of Cryptocurrency"
      venue: "Consumers' Research - DACOR Bacon House"
      address: "1801 F Street, NW"
      city: "Washington, DC"
      country: "United States"
      link: "http://consumersresearch.org/event/the-age-of-cryptocurrency/"
![book cover](https://cloud.githubusercontent.com/assets/11631203/6803315/18fac32c-d20d-11e4-9b45-685d3e74404b.jpg)

**Comment by harding** [comment]
@ConsumersResearch thanks for submitting your event!  It should appear on the website within 15 minutes.
