### ISSUE TITLE
full node os x?  

### ISSUE THREAD

**Issue by jmdugan** [bitcoin/bitcoin.org#795]
trying to run a full node on os x, instructions say to add issue and I can provide screen shots.

please let me know what you need to help fill in here:
https://bitcoin.org/en/full-node#mac-os-x-instructions

also, under settings, when is says "size of database cache" - is that the same as the 50GB listed above on instruction page (here: https://bitcoin.org/en/full-node#minimum-requirements) because the interface does not allow me to run that up to 50GB.

Do I simply need to get the bitcoin-qt and keep it running?  will it download the whole blockchain by default?

**Comment by harding** [comment]
@jmdugan Hi!  Thanks for volunteering.  The instructions for contributing to the doc are basically the same as I gave to someone else for Windows 8 here: https://github.com/bitcoin/bitcoin.org/issues/763

No, the database cache is how much you want to keep in memory (RAM).  Keeping more in memory improves the performance of your node; keeping less makes it slower to respond to queries.  The default setting is fine for all nodes running on desktop/laptop computers less than 10 or 15 years old.  (That setting is really for people who want to run Bitcoin Core on lightweight computers like the Raspberry Pi 2.)

Yes, just start bitcoin-qt and keep it running.  It will download the whole block chain by default, showing you its progress in the orange progress bar at the bottom.  When that bar disappears, you're fully synced to the block chain.  Also read the [section in the guide](https://bitcoin.org/en/full-node#network-configuration) about configuring your network, if necessary, to allow inbound connections.

If you have any other questions while taking the screenshots and writing notes, please don't hesitate to ask.  Thanks!

**Comment by harding** [comment]
Closing.  This has been idle for two months and someone else has volunteered.
