### ISSUE TITLE
Bitcoin in the City

### ISSUE THREAD

**Issue by anthonyc0603** [bitcoin/bitcoin.org#797]
A series of 5 lectures on Bitcoin organised by Roolo, the City Bitcoin Company behind the new peer to peer bitcoin trading site roolo.io.  The series is for people who want to understand how Bitcoin works and why its will revolutionise the way that people do business in the City.  

Lectures are 6-7pm each Wednesday evening with 1 hour of networking afterwards.

Starting 1 April 2015 for 5 weeks

Hosted by SAS at their offices at. 
7th Floor
199 Bishopsgate
London
EC2M 3TY

Full details https://events.roolo.io

**Comment by harding** [comment]
@anthonyc0603 thanks for submitting your event!  It should appear on the website within 15 minutes.
