### ISSUE TITLE
Bitcoin and Electronic Crime - APWG eCrime 2015

### ISSUE THREAD

**Issue by davejevans** [bitcoin/bitcoin.org#803]
- date: 2015-05-26
      title: "Bitcoin and Electronic Crime - APWG eCrime 2015"
      venue: "CaixaForum / Casa Ramona"
      address: "Av. Francesc Ferrer i Guàrdia, 6-8 "
      city: "Barcelona"
      country: "Spain"
      link: "http://www.apwg.org/apwg-events/ecrime2015/"

**Comment by harding** [comment]
@davejevans thanks for submitting your event!  It should appear on the site within 15 minutes.
