### ISSUE TITLE
AML Compliance Bootcamp for Digital Currency

### ISSUE THREAD

**Issue by Erikazeee** [bitcoin/bitcoin.org#804]
- date: 2015-04-30
      title: "AML Compliance Bootcamp for Digital Currency"
      venue: "New York City"
      address: ""
      city: "New York City"
      country: "United States"
      link: "http://www.digitalchamber.org/bootcamp.html"

**Comment by Erikazeee** [comment]
THE CHAMBER OF DIGITAL COMMERCE INVITES YOU TO
 AML Compliance Bootcamp
AT
NEW YORK CITY
APRIL 30 - MAY 1, 2015
 
Optional Workshop: May 2, 2015
Digital currency companies:  Tackle the tough issues necessary to develop banking relationships
Bankers: Develop strategies to gain regulatory confidence to bank virtual/digital currency businesses
Gain critical compliance skills and learn how to deal with government regulations
Satisfy federal training requirements and collect important continuing education credits (ACAMS, CLE, CSBS, DCC, and more)
 
In this intense and interactive two-day program, you’ll discover how to make sure your AML compliance efforts meet banks' and regulators' expectations and how to prepare for your next AML compliance review from your bank, regulators or an independent auditor.
 
In an optional third day, focus on the mechanics of your written program. Participants will work with their peers applying teachings from the bootcamp to draft/revise a risk assessment and other AML compliance program documents.

**Comment by harding** [comment]
@Erikazeee do you have the specific address for this event?

**Comment by harding** [comment]
Closing, we never received a specific address and the event is now in the past.
