### ISSUE TITLE
help

### ISSUE THREAD

**Issue by johnconstantine750** [bitcoin/bitcoin.org#811]
Running A Full Node using Windows 8.1

**Comment by harding** [comment]
@johnconstantine750 thanks for offering to help!  I provided instructions for what needs to be done in the following issue: https://github.com/bitcoin/bitcoin.org/issues/763

I'm going to close this issue just so we don't have two issues for the same thing.  Please comment on the other issue if you have any questions, or send me an email <dave@dtrt.org>  Thanks again!
