### ISSUE TITLE
In which license is available Bitcoin.org content?

### ISSUE THREAD

**Issue by paladini** [bitcoin/bitcoin.org#817]
I want to know a very basic thing: in which license is available Bitcoin.org content (FAQ, tutorials, etc.)?

In the footer of the website we can found that the website is licensed under the MIT license, but MIT licensed is used only for code, right? I also have looked at Legal disclaimer and the Frequently Asked Questions section, but I couldn't find the answer.

In which license is available Bitcoin.org content? CC BY 3.0? CC BY 4.0? MIT?

**Repo collaborators:** please add "Help Needed" label.

**Comment by harding** [comment]
@paladini the MIT license, as stated.  You can also check the [COPYING file](https://github.com/bitcoin/bitcoin.org/blob/master/COPYING) in the repository, which says;

> The intellectual property rights in the files are owned by the respective authors. Some of the files can be licensed under MIT License (MIT) available on http://opensource.org/licenses/MIT or other licenses. Appropriate licensing information can be found in the header of the file or in the folder containing the file.

In general, text files have the license information near the top and image files have the license information in a file in the directory.

Does that answer your question?

P.S. the help needed label is for when the usually contributors to the repository need help, not for when users need help.  Maybe I can think of a better name; I stole help needed from Debian's BTS.

**Comment by paladini** [comment]
Thanks for your fast reply!

Just to check if I've understood: the FAQ, located at https://github.com/bitcoin/bitcoin.org/blob/master/_templates/faq.html, is licensed under MIT terms (header of the file), so I can use the Bitcoin.org FAQ for anything I want if it respects the MIT license, correct? 

Summarizing: if a file or a section doesn't specify a license, I should consider this as a content licensed under MIT, right?

**Comment by saivann** [comment]
@paladini Yes. However, certain pictures listed on the page are not MIT licensed (see the COPYING file here: https://github.com/bitcoin/bitcoin.org/tree/master/img/faq). This being said, although I am not a lawyer, I think you can easily use screenshots like this without much copyright issues.

**Comment by paladini** [comment]
Thank you so much @saivann ! I should link this Issue to Bitcoin StackExchange and Reddit.

Thank you, guys!

**Comment by saivann** [comment]
@paladini Re: "if a file or a section doesn't specify a license, I should consider this as a content licensed under MIT, right?"

Sorry I missed this part of your question. If you don't see a license, then it's better not to assume it is MIT licensed and ask for clarification (all the work we do is MIT licensed but it can happen that we use content from elsewhere under a different license). Currently all files in the repository should have a license header or a COPYING file in their directory, so you should have the information you need.
