### ISSUE TITLE
Bitcoin Paper by Satoshi Nakamoto translated into Spanish

### ISSUE THREAD

**Issue by breathingdog** [bitcoin/bitcoin.org#822]
This is the Bitcoin Paper by Satoshi Nakamoto, translated into Spanish.

PDF viewer online link: http://www.viewdocsonline.com/document/9ky4ok
MEGA download link: https://t.co/3eK4aZqiPj

I've worked side by side with a translator to achieve a translation set to the original not only in content, but also in form and aesthetics.

Hope you consider it appropiate to be uploaded to the site to help Spanish speakers to understand more deeply how Bitcoin works. Thanks.

**Comment by jgarzik** [comment]
+1 I had recommended filing this issue on twitter.

I think we need to get a couple independent Spanish-speaking reviewers to ACK

**Comment by franckuestein** [comment]
Great work @breathingdog!

---
As well, +1 @jgarzik. 
If you need help with translations, just let us know. In my case I'm helping with some Spanish and Catalan translations for bitcoin-related projects on [Transifex](https://www.transifex.com/accounts/profile/franckuestein/).

**Comment by harding** [comment]
How does this new translation compare to the latin-american Spanish transaction currently on the site?  https://bitcoin.org/bitcoin_es_latam.pdf  Is this using continental Spanish?  (Sorry if I'm asking stupid questions; I don't know too much about Spanish dialects.)

**Comment by saivann** [comment]
It seems like the link to the Spanish PDF isn't applied on this page:
https://bitcoin.org/es/como-funciona
(maybe it was replaced by mistake by one translator, or it was only linked from the development page previously, which now links to an English-only page):

Maybe we could also link to the translated versions (currently Spanish and Russian) on:
https://bitcoin.org/en/developer-documentation

@breathingdog I too would appreciate your insight on what to do with your translation and the existing one. Also, if we end up uploading any new version, could you work with one of the .odt documents I have created previously for this purpose (https://github.com/saivann/bitcoinwhitepaper#usage)? Keeping the original .odt file makes it's easier to make further changes if needed, and this document contains the illustrations in a vector format that will scale and display correctly once exported in PDF on bitcoin.org (and this should also reduce its size).

**Comment by franckuestein** [comment]
@harding & @saivann: spanish, despite being one of the most spoken languages ​​worldwide, retains considerable homogeneity.

First of all, the document that @breathingdog shared it's translated to Spanish from [Spain](http://en.wikipedia.org/wiki/Spain), the other one was translated by Angel León from www.diariobitcoin.com to latin-Spanish.
If you take a look to their website, you're going to see some tags like: 'chile','mexico','latinoamerica' and many more latin countries[1].

But, what's the difference? There are noticeable linguistic differences between the Spanish from Spain and the Spanish from latinamerica. Both speech and writing have notable differences, you can take a look to some (as reference) on [Wikipedia](http://es.wikipedia.org/wiki/Anexo:Diferencias_de_léxico_entre_pa%C3%ADses_de_lengua_española).

*And don't think that you're asking stupid questions, they're normal questions.* :smile:
Hope to help you!

---

[1]: [Graphic with Latin countries (left) and Spain (right).](http://www.negocioos.com/imagenes/map.jpg)

**Comment by breathingdog** [comment]
@harding, as @franckuestein wrote, Spanish retains high homogeneity worldwide. The document is translated into Spanish from Spain –I'm from Spain, more concretely from Canary Islands, islands that have tight links to Latin America, must be said. Probably any Spanish speaker in the world from Mexico to Argentina, from Philippines to Equatorial Guinea, will understand this translation with no problem, like any English speaker would understand one document written in English from the UK or USA.

@saivann, about the first point, I consider the existing latin-american translation is of course notable but it's like having a Canadian-English or South Africa-English translation for all English speakers, which is good but not 100% proper. Probably the best is they co-exist.

In León's translation there are some technical terms, like "timestamp", that are commonly and legaly used in Spanish as "sellado de tiempo", which León translates as "marcas de tiempo". Not incorrect, but always prefered to attach myself to the technical and legal most frequent use of each concept.

Some other concepts, like "peer-to-peer" or "proof-of-work", has been correctly translated into Spanish, but as far as they continue being used more frequently in English than in Spanish, I've found more accurate to maintain these terms in English and add a link to Wikipedia, where the reader can have more information about them than translated terms itselves give. He also doesn't keep in cursive all the English words he keeps in the text, which may induce into confusion. Cursive for foreign terms is a must.

Some sentences have been translated verbatim, which leads to structures that are not correct in Spanish and inappropiate for an accurate reading. There is an abundance of use of gerund, which is not as common in Spanish as it is in English. The reference to the fan-out issue in point 9 has been omitted, for instance. Let me add that above all the text is understandable, but personally I found the Bitcoin Paper needs a more precise and accurate translation.

I'm not a professional translator but been translating for years, and I've worked this time side by side with a profesional ENG-ESP translator, looking for that equilibrium, knowledge and skills. Of course any tip, improve or correction is welcome.

@saivann thanks for the .odt blank file. I'll try and update my translation as far as I can. I decided to use images not vector because I couldn't keep the schemes in the same proportions as the original. I'll try with this file because I agree you, the document is much better in vector.

**Comment by breathingdog** [comment]
@saivann one question: how can I move text within the vector graphics. Text boxes seem to be fixed or anchored somewhere but I cannot unlock them to fit text and align it properly. Thanks.

**Comment by harding** [comment]
@breathingdog I looked into it, and I think @saivann is wrong about those images being in vector format.  Looking at the document source, they're base64-encoded PNGs.  I think LibreOffice just has some way of letting you cover over existing text with new text.

I'll make up some true SVGs and open a pull request to the bitcoinWhitePaper repository with them.

**Comment by harding** [comment]
Correction: those images are in vector format, but it's LibreOffice Draw rather than pure SVG.  I'll figure out what to do with them in a few minutes.

**Comment by saivann** [comment]
@harding @breathingdog Editing more than just texts can be a bit more difficult if you are not used to LibreOffice Draw. If the text doesn't fit well, I think we can adapt the drawing to it afterwhile. Otherwise, the first step to edit the drawing (at least AFAIK, there might be an easier way), is to copy paste the picture in Libreoffice Draw and then click "Modify / Dissociate" to be able to edit individual parts of the drawing. Later once the drawing is updated, it can be paste back into the document and re-adapted to the text like the previous picture.

**Comment by breathingdog** [comment]
@harding @saivann They are in vector, yes. I think it's preferable to change the space between characters rather than changing the visual aspect of the drawing, which is something I'm trying now and it seems to work.

I was working on what you say, copying the drawings in AOO Draw, working on them there and then taking them back to AOO Write. The only problem I'm finding by now is to anchor the corrected draws exactly the same.

**Comment by saivann** [comment]
@breathingdog What works fine in my case is to copy the picture back into the document (over the previous one). Than, I right-click on the picture and go to "Anchor / As character". Then the result is identical the the initial document, with the updated picture. (French screenshot below).

![capture du 2015-04-13 13 18 40](https://cloud.githubusercontent.com/assets/3578089/7121045/b15742bc-e1df-11e4-9d1d-401575dd8873.png)

**Comment by saivann** [comment]
@breathingdog @franckuestein Thanks for your explanations! Let's keep both translations then.

**Comment by breathingdog** [comment]
@saivann Perfect! It works now! Thanks! ASAP I will re-upload the vector version using the template you provided.

**Comment by breathingdog** [comment]
Hello again. Here I attach a MEGA link and a PDF online viewer link to the last version of the translation.

MEGA: https://mega.co.nz/#!i1wkmRwQ!sNk-Umm7fXeb3RtuKFCqVQdXbB3aZqVcQomD3iaEqDo
Online viewer: http://www.viewdocsonline.com/document/ff4i9l

Now I've worked on the .odt document. Thanks to that, I've been able to improve the schemes, placing Spanish terms more properly in them. Only one of them, "9. Combinando y diviendo valor", has been slightly increased in width.

Apart from that, when you translate from ENG to ESP, you know you're going to have more words than in the original document (should be added to universal constants lol). I've slightly modified upper and lower margins of the document –which is permissible, in order to mantain the structure of the original text and avoid ugly and/or distracting page breaks.

Thanks!

**Comment by saivann** [comment]
@breathingdog Sorry for the delayed response. That looks very good! Can you provide the .odt document so we can have the source should we need to edit the file? I should have more time soon to check the file more in-depth.

Also do you think you could add the same mention about the author of the translation in the header as other currently published translations? For example:

~~~
Translated in French from bitcoin.org/bitcoin.pdf
by ...
~~~

**Comment by breathingdog** [comment]
@saivann I've been traveling, no worry at all. About mentioning the author of the translation in the header, I've asked the translator that helped me and she considers it would be intrusive for the text. Also, it would cause the paragraph to misalign completely compared to the original.

There's a controversy between translators who want their name to appear front-end and those who think it must appear but as part of the technical data –non-intrusive. This second position I like the most, but if you don't accept the document without a header-in mention, it shall be modified.

Here's a link to MEGA with the .odt document: https://mega.co.nz/#!utoknT7K!n_D_mMUgbxQbqeqQN5nCPk36N4OnRCNxXITVln1Nuos

**Comment by harding** [comment]
@breathingdog I'm reading through a Google Translate re-translation of the document and everything is good so far, but in section 4 "Adam Black" should be "Adam Back".  (You have the correct spelling in the references section at the end.)

**Comment by breathingdog** [comment]
OMG @harding THANKS!! I'll fix it asap!!

**Comment by breathingdog** [comment]
Here it goes updated with Black fixed to Back.

MEGA download link: https://mega.co.nz/#!Po4yGDSa!ZqsCWSqLL-bn0ibh4mKtwfF9SIar5x4SUnynkpxKM_Q

PDF viewer online: http://www.viewdocsonline.com/document/10r1nk

**Comment by saivann** [comment]
The updated PDF and .odt file look good to me too, thanks!

@harding Given the existence of various vulnerabilities around PDF files, just as a precaution, it might be good to always generate the final PDF from the .odt file by ourselves and scan it for vulnerabilities with virustotal.com? I wouldn't be against hosting the .odt files on this repository too if that makes things more simple.

**Comment by harding** [comment]
@saivann actually, I did generate the PDF of this translation included in PR #839 to ensure that it had exactly the same translation I reviewed.  (I used LibreOffice's *preview in web browser* feature → Chromium → Translate This Page).

However, making that a formal policy sounds like a good idea.  How about I add a Liquid `[% comment %}` above the list in the `_templates/bitcoin-paper.html` file saying what you said about generating the PDFs ourselves and scanning them for viruses?  (I'll add this to PR #839.)

**Comment by breathingdog** [comment]
@harding If you have generated the PDF from the .odt, please check and correct Black to Back in section 4, because I'm realizing I did not sent any .odt fixed, just the PDF.

**Comment by harding** [comment]
@breathingdog yep, I noticed and fixed it myself. :-)  Thanks though!

**Comment by breathingdog** [comment]
@harding thumbs up! :)

**Comment by saivann** [comment]
@harding Sounds good. Although perhaps the README would be more suited for this type of instruction? Kudos for being so careful :) .

**Comment by harding** [comment]
@saivann In general, I think documentation is best placed closest to where it will be used, otherwise people are more likely to miss it.  That is, just because the file is named README doesn't actually mean anyone actually reads it. :-)

**Comment by harding** [comment]
Closing as this was added in https://github.com/bitcoin/bitcoin.org/commit/d383940ecb5caaaedff50f8d366acd8d1dc806ec  Thanks everyone!
