### ISSUE TITLE
I can provide instructions/screenshots for installing Bitcoin Core on Windows 8 (similar to 8.1; I can write the differences)

### ISSUE THREAD

**Issue by veqtrus** [bitcoin/bitcoin.org#825]
I will follow the instructions on #763

**Comment by harding** [comment]
@veqtrus excellent.  Thanks!

**Comment by veqtrus** [comment]
HTML: http://veqtrus.coffeecup.com/bitcoin_core/instructions.html
Markdown: http://veqtrus.coffeecup.com/bitcoin_core/instructions.md
Compressed folder: http://veqtrus.coffeecup.com/bitcoin_core/instructions.zip

The only difference in Windows 8.1 is that you can open the start screen from the task-bar as well.

**Comment by harding** [comment]
@veqtrus awesome, thanks!  I'll probably have a chance to look at this tomorrow.  Thanks again!

**Comment by gurnec** [comment]
@veqtrus This looks great!

I've two small suggestions.

You (excellently) note to edit the file permissions of bitcoin.conf, but it might be better to spell out exactly how to do so. This could otherwise be a bit confusing for some—for example it's not obvious that you must disable permission inheritance under Advanced settings before you can remove permissions.

Second: here's a [screenshot of the UAC install prompt](http://i.imgur.com/EO3eWqk.png). If you'd like to create your own, you need to temporarily: Start -> run, "secpol", Local Policies -> Security Options -> "User Account Control: Switch to the secure desktop when prompting for elevation" -> Disabled (no reboot required).

**Comment by veqtrus** [comment]
@gurnec Thanks, updated.

**Comment by harding** [comment]
@veqtrus I'm writing this up right now (sorry for the delay).  Do you know if Bitcoin Core prompts for the storage location the first time it is started like it does for other platforms?  For example, see:

https://bitcoin.org/img/full-node/en-win7-welcome-to-bitcoin-core.png

If it does, I'd like to skip the `mklink` instructions.

**Comment by gurnec** [comment]
@veqtrus I'm sorry for the delay, but regarding the permissions... I had thought you were thinking of removing read access from everyone but the current user to somewhat safeguard the RPC password, but perhaps you had something else in mind?

**Comment by veqtrus** [comment]
@harding Mine didn't probably because the directory already existed. I'll try to remove it and install again.

@gurnec I removed write access so that a virus which would run as a normal user couldn't alter the file. The RPC interface IIRC binds to localhost by default and can't be used to send bitcoins without the wallet password. Do you think I should remove read access as well?

**Comment by gurnec** [comment]
@veqtrus After thinking about this for a bit, I'm of the opinion you should just remove the permissions change step.

From what I can tell, the directory permissions in your screenshot are not what should be expected on a typical Windows box (when I check two Win7 and one Win8 box I have easy access to, they already have restrictive permissions for that directory). Is your Windows install the result of upgrading from a version of Windows prior to Win7?

I think explaining how to get the permissions correct, if they're not already correct, will be tricky for those not already familiar with NT permissions. For example, in the instructions you provided, you didn't limit access to the *Authenticated Users* group but probably should have. Even if you did, malware running under the same user account as runs bitcoind can always read or modify the file (as the file owner, it can change the permissions to whatever it likes).

All this seems too complex to get into for a "simple" howto IMO....

**Comment by harding** [comment]
@veqtrus I've written up instructions based on your notes and using several of your sceenshots.  You can find the pull request for them here: https://github.com/bitcoin/bitcoin.org/pull/838

Thank you so much for all of your help!
