### ISSUE TITLE
BL0CKCHA1N: The Blockchain Forum

### ISSUE THREAD

**Issue by Finyear** [bitcoin/bitcoin.org#833]
- date: 2015-06-11
      title: BL0CKCHA1N: The Blockchain Forum
      venue: Novotel Paris Centre Tour Eiffel
      address: 61 quai de Grenelle, 75015
      city: PARIS
      country: France
      link: http://www.bl0ckcha1n.com

**Comment by harding** [comment]
@Finyear thanks for submitting your event!  It should appear on the website within about 15 minutes.  Reference commit: https://github.com/bitcoin/bitcoin.org/commit/3a7968eee4ac59a4e632e939da144c5e1772ae7d

**Comment by Finyear** [comment]
Hello David,

The Bl0ckCha1n Forum date has changed. It is now set for November the 3rd, 2015.
The original date was too close to french school vacations, and besides, several speakers were unable to attend to the event.

Please let me know when our listing is updated.

Best regards,

Pierre Leloup

Finyear.com
Premier quotidien Finance & Gestion
XPR.io
Expérience + Expertise partagées | Plateforme de solutions d'entreprise

Your comments and inquiries are always welcome. As a true Internet entity we don't respond to phone calls or to postal mails. 
Please note that due to the large number of daily emails we receive we can not always meet in the day.

Vos commentaires et vos demandes sont toujours les bienvenus. En tant qu'authentique entité Internet, nous ne répondons pas aux appels téléphoniques ou au courrier postal. Veuillez prendre note qu'en raison du grand nombre de courriels que nous recevons quotidiennement, nous ne pouvons pas toujours répondre dans la journée.


This message and any attachments (the "message") is intended solely for the intended addressees and is confidential. If you receive this message in error,or are not the intended recipient(s), please delete it and any copies from your systems and immediately notify the sender. Any unauthorized view, use that does not comply with its purpose, dissemination or disclosure, either whole or partial, is prohibited. Since the internet cannot guarantee the integrity of this message which may not be reliable, our company (and its subsidiaries) shall not be liable for the message if modified, changed or falsified.
Do not print this message unless it is necessary,consider the environment.

**Comment by harding** [comment]
@Finyear sorry, I forgot to reply here.  The website has been updated.  Thanks for notifying us!
