### ISSUE TITLE
Anti-Money Laundering Compliance Bootcamp for Digital Currency

### ISSUE THREAD

**Issue by erika13** [bitcoin/bitcoin.org#834]
- date: 2015-04-30
      title: Anti-Money Laundering Compliance Bootcamp for Digital Currency, hosted by the Chamber of Digital Commerce
      venue: NY
      address: ""
      city: NY
      country: USA
      link: http://digitalchamber.org/bootcamp.html

**Comment by harding** [comment]
@erika13 that you for submitting the event.  We already have issue #804 open for this event, and we need the specific address to add it to our site.

I'm going to close this duplicate issue; when you have the specific address, can you please add it as a comment here: https://github.com/bitcoin/bitcoin.org/issues/804

Thanks!

**Comment by erika13** [comment]
Thanks for the update! I'll add the venue address when it is released.
ᐧ

Erika Zapanta
Assistant Account Coordinator
Transform Public Relations
Cell: 702-503-1239
Skype: Erika Zapanta
http://transform.pr/
