### ISSUE TITLE
Incorrect reference to offline wallet in developers guide

### ISSUE THREAD

**Issue by cbaumler** [bitcoin/bitcoin.org#835]
Source File: _includes/guide_wallets.md

The developers guide refers to an offline wallet when it should be referring  to a signing-only wallet for consistency.

*Original text:*
After the optional review step, the **offline wallet** uses the parent private key to derive the appropriate child private keys and signs the transactions, giving the signed transactions back to the networked wallet.

*Suggested revision:*
After the optional review step, the **signing-only** wallet uses the parent private key to derive the appropriate child private keys and signs the transactions, giving the signed transactions back to the networked wallet.

**Comment by harding** [comment]
@cbaumler thanks!  I implemented your suggested fix; it should appear on the website within about 15 minutes.  Thanks again!

**Comment by cbaumler** [comment]
No problem. Thanks for providing this excellent developer guide.
