### ISSUE TITLE
Bitcoind/Windows 8.1 (Newbie Question.)

### ISSUE THREAD

**Issue by GrovesideGreg** [bitcoin/bitcoin.org#841]
Hello,
How do I configure 'getgenerate' to return 'true' instead of 'false?'
 Thank you.

![getgenerate](https://cloud.githubusercontent.com/assets/11382653/7335371/ace2c3f4-eb86-11e4-810d-7ee5ff410460.PNG)

**Comment by harding** [comment]
@GrovesideGreg I'm sorry, we don't provide support for Bitcoin Core here.  You can ask your question in one of the communities linked from this page: https://bitcoin.org/en/development#devcommunities
