### ISSUE TITLE
Remove Bootstrap Torrent From Bitcoin.org

### ISSUE THREAD

**Issue by harding** [bitcoin/bitcoin.org#846]
I just saw [this post on Reddit](http://www.reddit.com/r/Bitcoin/comments/349g8l/help_speed_up_bitcoin_qt_wallet_syncing_by/) where people are still recommending using the bootstrap torrent to download the block chain before starting Bitcoin Core.  Since that is no long advantageous on newer versions of Bitcoin Core, I suggest that we remove the torrent from [this directory](https://bitcoin.org/bin/blockchain/) and replace the contents of README.txt with something like:

    The block chain bootstrap torrent formerly hosted here will not speed up
    downloading the block chain on Bitcoin Core 0.10.0 or later.  If you install
    the most recent version of Bitcoin Core[1], it will sync itself as fast as
    possible.

    [1] https://bitcoin.org/en/download

CC: @jgarzik

**Comment by instagibbs** [comment]
perhaps "typically as fast as the internet connection allows" or something like that.  

Otherwise ACK

**Comment by saivann** [comment]
@harding Jeff wanted to keep serving the torrent for academic purposes. Given that Jeff is also serving the torrent via his own server, I suggest we keep a line to his thread:

https://bitcointalk.org/index.php?topic=145386.0

**Comment by jgarzik** [comment]
Indeed I think it is still useful and am about to update it.  HOWEVER, it should not be recommended anymore as the best means to get the blockchain.

Just updated the forum page to include such a disclaimer.

**Comment by harding** [comment]
Here's replacement text for the README based on @jgarzik's forum upate:

    As of Bitcoin Core version 0.10.0 and later, the block chain bootstrap
    torrent formerly hosted here is *slower* than a direct download using
    the bitcoin P2P protocol & client.  If you want the torrent for other
    reasons, please visit:

        https://bitcointalk.org/index.php?topic=145386.0

    To download the latest version of Bitcoin Core, please visit:

        https://bitcoin.org/en/download

**Comment by harding** [comment]
@saivann would you be able to handle updating this on the production server?

**Comment by jtimon** [comment]
+1

**Comment by jgarzik** [comment]
I agree with marking it as "for academic use only" and other warnings.

My preference is to keep the torrent however.  Simply being able to download the blockchain without a special client has value -- just the *primary* value has now been removed as of 0.10.

**Comment by jgarzik** [comment]
One tactic could be as simple as renaming the torrent filenames themselves, to intentionally break existing links.

**Comment by jtimon** [comment]
Renaming the torrents and explaining why sounds like a good plan.

**Comment by harding** [comment]
Renaming the directory sounds fine to me.  Here's some text which can be added to the top of the README.txt file:

    **Note:** As of Bitcoin Core version 0.10.0 and later, the block chain
    bootstrap torrent hosted here is *slower* than a direct download using
    the Bitcoin P2P protocol & client.

That file already links to the forum thread, so anyone who wants to learn more can go there.

**Comment by saivann** [comment]
Sounds good. I've renamed /bin/blockchain/ to /bin/block-chain/ and included the header in the README. Just let me know if you consider other changes are necessary.

**Comment by harding** [comment]
@saivann thanks!
