### ISSUE TITLE
Coin Congress San Francisco 2015

### ISSUE THREAD

**Issue by coincongressevents** [bitcoin/bitcoin.org#848]
date: 2015-08-13
  title: "Coin Congress San Francisco 2015"
  venue: "Hilton Union Square - San Francisco"
  address: "333 O'Farrell St"
  city: "San Francisco"
  country: "USA"
  link: "http://www.coincongressevents.org"

**Comment by harding** [comment]
@coincongressevents thanks for submitting your event!  It should appear on the website within about 15 minutes.
