### ISSUE TITLE
III Brazilian Bitcoin Conference

### ISSUE THREAD

**Issue by wladcrippa** [bitcoin/bitcoin.org#858]
- date: 2015-07-18
      title: "III Conferência Brasileira sobre Bitcoin - III BitConf"
      venue: ""
      address: ""
      city: "Florianópolis"
      country: "Brazil"
      link: "www.bitconf.com.br"

**Comment by coderwill** [comment]
@wladcrippa - hello, please provide the venue and address.

**Comment by wladcrippa** [comment]
venue and address to confirm in next days
