### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by bitkeef** [bitcoin/bitcoin.org#864]
- date: 2015-09-10
      title: "Consensus 2015"
      venue: "TimesCenter"
      address: "242 W 41st St"
      city: "New York"
      country: "United States"
      link: "http://www.coindesk.com/events/consensus-2015/"

**Comment by harding** [comment]
@bitkeef thanks for submitting your event!  It should appear on the website within about 15 minutes.

**Comment by bitkeef** [comment]
Thanks, that's awesome!
