### ISSUE TITLE
wrong definition for cross-reference link on "header"

### ISSUE THREAD

**Issue by aliakbarahmadi** [bitcoin/bitcoin.org#867]
Location: https://bitcoin.org/en/developer-reference#message-headers

It says "The header format is:" with "header" having wrong definition when hovering over it with the mouse. Correct cross-reference link should be to definition for "message header"!

**Comment by harding** [comment]
@aliakbarahmadi thanks for reporting this!  It should be fixed on the website within 15 minutes.
