### ISSUE TITLE
avalbit Presentation

### ISSUE THREAD

**Issue by gonxi** [bitcoin/bitcoin.org#872]
- date:2015-05-28
      title: "Presentation of avalBit "
      venue: "Las naves"
      address: "Juan verdeguer 16"
      city: "Valencia"
      country: "spain"
      link: "http://avalbit.org"

**Comment by harding** [comment]
@gonxi is there a typo? Your event date was almost a week ago.

**Comment by gonxi** [comment]
The date is correct. IT is to record the event. Is possible?I did not know I could post events here

**Comment by harding** [comment]
@gonxi no, we don't list historic events, but thank you for submitting anyway!

**Comment by gonxi** [comment]
Ok!  The next! ;)
