### ISSUE TITLE
Bitcoin Development Workshop

### ISSUE THREAD

**Issue by Bitcoin-dev** [bitcoin/bitcoin.org#876]
- date: 2015-06-20
      title: "Bitcoin Development Workshop 2015"
      venue: "De War"
      address: "Kleine Koppel 40, 3812 PH"
      city: "Amersfoort"
      country: "Netherlands"
      link: "http://bitcoinmeetup.nl/2015/06-20.html"

**Comment by harding** [comment]
@Bitcoin-dev your event is now listed on the website---thanks for submitting it! https://bitcoin.org/en/events
