### ISSUE TITLE
Confusing/Incomplete wording?

### ISSUE THREAD

**Issue by aliakbarahmadi** [bitcoin/bitcoin.org#877]
Location: https://bitcoin.org/en/developer-guide#term-unsolicited-block-push

Based on my question about "http://bitcoin.stackexchange.com/questions/37807/block-broadcasting-unsolicited-block-push" and received answers from an active moderator, Nick ODell, I was confused by reading the paragraph about unsolicited block push.

It says: "the miner sends a block message to each of its full node peers with the new block."
But: Apparently the block message is sent to a peer only then, when this newly mined block is requested upon receiving an inv message from the miner of the new block. [1] And this fact is not deductiv from the current paragraph.

Further it says: "The miner can reasonably bypass the standard relay method in this way because it knows none of its peers already have the just-discovered block."
Request: Could you, please if you have time, give some additional information on the standard relay method or refer to an already mentioned definition for it or to the source code, where this is implemented?  

Thanks in advance!

____Sources_____________________________________________________________________
[1] http://bitcoin.stackexchange.com/questions/37807/block-broadcasting-unsolicited-block-push/37808?noredirect=1#comment44293_37808 - and following comments.

**Comment by harding** [comment]
@aliakbarahmadi I added a sentence yesterday after reading your question that hopefully fixes the problem.  See https://github.com/bitcoin/bitcoin.org/commit/b847610e1b129a85b3fd00c251b97864f2f89781

(I also commented on Nick's answer with a link to the above.)

Please let me know if you need more information.

**Comment by luke-jr** [comment]
An example unsolicited block push can be found in Eloipool: https://github.com/luke-jr/eloipool/blob/master/bitcoin/node.py#L176

**Comment by aliakbarahmadi** [comment]
@harding Thanks! It was important to me to know what's the default procedure of broadcasting a newly found block.
@luke-jr Thanks to you, it's good to know that unsolicited block broadcast is used in practice, too. Is Eloipool a pool and if yes, does each pool determine it's broadcasting behaviour?

I'm going to test a scenario of block mining with multiple test nodes on regtest. What broadcasting method is used in regtest? The Standard Block Relay?

**Comment by luke-jr** [comment]
@aliakbarahmadi Eloipool is the poolserver software I wrote for Eligius.

**Comment by harding** [comment]
@aliakbarahmadi yes, the standard block relay is used between peers on regtest.

I'm going to close this issue as it seems that the concern has been addressed.  Let me know if I missed something.
