### ISSUE TITLE
Controlling Crypto-Currencies ~ Live Webcast

### ISSUE THREAD

**Issue by switchnewmedia** [bitcoin/bitcoin.org#883]
- date: 2015-12-06
      title: "Live Webcast: The International Controlling Crypto-currencies Conference
      venue: "University of Birmingham"
      address: "Worcester Room, Hornton Grange"
      city: "Birmingham"
      country: "England"
      link: "http://switchnewmedia.com/crypto-currencies/live.html"

**Comment by coderwill** [comment]
@harding recommending we close this issue since the event has already passed.

**Comment by harding** [comment]
@coderwill oh, indeed.

@switchnewmedia I'm very sorry I didn't get to posting your event in time.  I thought the date was for December not June, so I didn't rush to post it.
