### ISSUE TITLE
can't translate a string in FAQ

### ISSUE THREAD

**Issue by norill** [bitcoin/bitcoin.org#884]
the string "General" below ToC in FAQ can't be translated

**Comment by coderwill** [comment]
@norill Hi there! Can you please provide more context on how exactly I can replicate the issue you're experiencing an issue translating the string? Happy to help resolve the problem!

**Comment by norill** [comment]
i can't find a way to translate that string on transifex. also its untranslated in every language e.g. 
https://bitcoin.org/ar/faq
https://bitcoin.org/ja/faq

**Comment by saivann** [comment]
It is translated in the table of content so my best guess is that it would
be easy to just fix the layout to make use that translation.

**Comment by harding** [comment]
Fixing now.  Thanks @norill, @coderwill, and @saivann!

**Comment by harding** [comment]
@norill the fix should appear on the website in about 15 minutes.  Thanks again!

**Comment by norill** [comment]
:+1:
