### ISSUE TITLE
Bitcoinference Summer 2015

### ISSUE THREAD

**Issue by Bitcoinference** [bitcoin/bitcoin.org#889]
- date: 2015-09-12
      title: "Bitcoinference Summer 2015"
      venue: "Amsterdam Science Park"
      address: "Science Park 205, 1098 XH"
      city: "Amsterdam"
      country: "Netherlands"
      link: "http://bitcoinference.com/"

**Comment by coderwill** [comment]
@Bitcoinference Hello, thanks for submitting your event. On your website, the stylesheet appears to be broken on your [Venue page] and it also appears that there are no speakers listed on the [Speakers page](https://bitcoinference.com/speakers.html) .

Could you please update these two items?

**Comment by Bitcoinference** [comment]
HI, stylesheet is working again. We don't yet have speakers registered for this edition.

**Comment by harding** [comment]
@Bitcoinference thanks for submitting your event.  It should appear on the website within about 15 minutes.
