### ISSUE TITLE
Minor: Correct Confusing Statment In /bin/block-chain/README.txt

### ISSUE THREAD

**Issue by harding** [bitcoin/bitcoin.org#892]
As [pointed out on #bitcoin-dev IRC](http://bitcoinstats.com/irc/bitcoin-dev/logs/2015/06/14#l1434292220.0), the statement I wrote for [/bin/block-chain/README.txt](https://bitcoin.org/bin/block-chain/README.txt) contains two confusions.  For reference, here is the statement:

    As of Bitcoin Core version 0.10.0 and later, the block chain bootstrap
    torrent formerly hosted here is *slower* than a direct download using
    the bitcoin P2P protocol & client.

1. The statement can be inferred to mean that  Bitcoin Core can **download** blocks using the Bitcoin P2P protocol faster than a torrent client can download them using the BitTorrent protocol.

2. The use of Markdown-style asterisk *emphasis* (`*emphasis*`) looks like a footnote reference.

Here is a revised statement that is hopefully more clear.

    As of Bitcoin Core version 0.10.0 and later, the block chain bootstrap
    torrent hosted here takes more time to download and import than it would
    to simply start Bitcoin Core and let it sync itself.

**Comment by saivann** [comment]
Updated

**Comment by harding** [comment]
@saivann thanks!  Closing.
