### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by martijnw** [bitcoin/bitcoin.org#893]
- date: 2015-06-26
      title: "HVA Blockchain blockstrap course"
      venue: "Amsterdam University of Applied Sciences"
      address: "Duivendrechtsekade 36-38"
      city: "Amsterdam"
      country: "Netherlands"
      link: "https://bitcoinembassy.nl/hva-blockchain-blockstrap-course-amsterdam-2015-06-26/"
![hva](https://cloud.githubusercontent.com/assets/2576442/8149633/e3f1d540-12ca-11e5-8419-af282406d45e.jpg)

**Comment by coderwill** [comment]
@martijnw Hi there, thanks for taking the time to mention this event and best wishes to you in terms of it being successful for you and the attendees. That said, I'm not sure how this meets the definition of an event in the context of other conferences or hackathons that we add to Bitcoin.org.

In particular, this line sticks out to me on your website:
>Complete the course and you’ll also qualify for a Free Professional Membership!

Perhaps @harding or another may have an opinion on this as well. They might disagree with me.

**Comment by martijnw** [comment]
This is a bitcoin workshop in cooperation with the University of applied sciences. Actually it is the first course of its kind in the netherlands. Attendees get a free membership to our non-profit organisation. It's a one day workshop and "Complete the course and you’ll also qualify for a Free Professional Membership!" we give all that succed a pro membership, the others get a free standard membership. It's a public event acceisble to all. Unlike the other event in The Netherlands ( https://bitcoin.org/en/events ) this one is free and actually has attendees! Why would you list an event like: https://bitcoin.org/en/events and ignore our event? Please clarfiy.

**Comment by martijnw** [comment]
@harding This goes against anything Bitcoin stands for. Decentralisation, democatisation and @coderwill find it astonishing that a blockchain event, organized by the Bitcoin Embassy Amsterdam (officially registered non profit) and accepted by a leading university here in Amsterdam is refused (such a major event!) as a listing on your site. The event is free and helps people educate about the blockchain and developing applications. It is not some sort of commercial scam so why in gods name do you refuse this course to be listed. What the hell do you guys think you are doing acting like f*cking dictators? 

@coderwill @harding This type of behavior raises very serious questions how certain people are hijacking and controlling certain fora and event listings. Maybe they are pushing their own personal agenda?

**Comment by harding** [comment]
@martijnw whoa, I haven't had time to look at this event yet, and Bitcoin.org has always been a friend to the Bitcoin embassies---see https://bitcoin.org/en/community#nonprofit-organizations

Please be patient.  I promise I'll review this today.

**Comment by martijnw** [comment]
Thanks Dave,

I have not been able to figure out how to list the non-profit
www.bitcoinembassy.nl to that page. The Github looks mighty democratic but
confusing for a non-programmer like me.

Kind regards,

Martijn Wismeijer
Bitcoin Embassy Amsterdam
www.BitcoinEmbassy.nl
contact@bitcoinembassy.nl
KvK registration #:  63009595

**Comment by harding** [comment]
@coderwill training sessions that are open to the public meet our criteria for events---recall that any Meetup.com event that includes the word "bitcoin" in its title gets shown on the map, so we're not especially picky.

@martijnw I apologize for the confusion.  Thank you for submitting your event---it will be added the site within the next half hour.

Also, I'll open a pull request to add Bitcoin Embassy Amsterdam to the non-profits page---I agree it's confusing, it confuses me sometimes!  I'll @ mention you so GitHub should send you an email when I open the pull request.  Thanks again.

**Comment by saivann** [comment]
@coderwill Thanks for taking a closer look at the events. Sometimes there are things that I find worth considering (e.g. down website or some worry that it may be a fraud). But otherwise, bitcoin.org thus far has really been open and permissive as to the content of the event itself, for as long as it's about Bitcoin.

**Comment by coderwill** [comment]
@martijnw I'm glad your event was added. I'm sorry as well for the confusion. The initial note was only to open up the convo, since your event hadn't been reviewed yet, and to invite @saivann and @harding (who make the final calls in most cases) to form their own opinion. Glad I was wrong and good luck with the event!
