### ISSUE TITLE
Bitcoin Conference Kiev 2015

### ISSUE THREAD

**Issue by voffkas** [bitcoin/bitcoin.org#895]
- date: 2015-09-15
      title: "Bitcoin Conference Kiev 2015"
      venue: "NSC Olimpiyskiy"
      address: "Velyka Vasylkivska str., 55"
      city: "Kyiv"
      country: "Ukraine"
      link: "http://bitcoinconf.com.ua/en"

**Comment by voffkas** [comment]
Can you fix date plesase?

- date: 2015-09-24

**Comment by justin130** [comment]
24 June 2015

Sent from my iPhone

On 18 Jun 2015, at 13:00, Voffkas <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you fix date plesase?

  *   date: 2015-09-24

-

**Comment by harding** [comment]
Sure, but note that your [website](http://bitcoinconf.com.ua/en) still says 24 Sept 2015.

**Comment by voffkas** [comment]
24 Sept 2015 - correct date

**Comment by harding** [comment]
@voffkas oh, ok.  I'll fix it again, but it'll take a few minutes.

**Comment by harding** [comment]
@voffkas the correct date, 24 Sept 2015, should be displayed on the site in about 15 minutes.  Thanks for letting us know.

**Comment by voffkas** [comment]
Thank you!
