### ISSUE TITLE
update mailing list

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin.org#907]
Mailing list has moved to LF.
* List: bitcoin-dev@lists.linuxfoundation.org
* Arch.: https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-dev

Updating https://bitcoin.org/en/development would be required.

**Comment by harding** [comment]
Fixed in  7b333dfb and aa5d54fdaf, which should be deployed within 15 minutes.  Thanks!
